server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/devops_labs.access.log;
    error_log /var/log/nginx/devops_labs.error.log;

    location = / {
        proxy_pass http://web:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /tasks {
        proxy_pass http://web:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 404;
    }
}